apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{open}} include "{{component}}.fullname" . {{close}}
  namespace: {{open}} .Release.Namespace | quote {{close}}
  labels:
    {{open}}- include "{{component}}.labels" . | nindent 4 {{close}}
spec:
  selector:
    matchLabels:
      {{open}}- include "{{component}}.selectorLabels" . | nindent 6 {{close}}
  template:
    metadata:
      labels:
        {{open}}- include "{{component}}.labels" . | nindent 8 {{close}}
    spec:
      {{open}}- with .Values.{{component}}.imagePullSecrets {{close}}
      imagePullSecrets:
        {{open}}- toYaml . | nindent 8 {{close}}
      {{open}}- end {{close}}
      {{open}}- with .Values.chartNodeSelector {{close}}
      nodeSelector:
        {{open}}- toYaml . | nindent 8 {{close}}
      {{open}}- end {{close}}
      {{open}}- if not .Values.chartNodeSelector {{close}}
        {{open}}- with .Values.{{component}}.nodeSelector {{close}}
      nodeSelector:
          {{open}}- toYaml . | nindent 8 {{close}}
        {{open}}- end {{close}}
      {{open}}- end {{close}}
      {{open}}- with .Values.{{component}}.affinity {{close}}
      affinity:
        {{open}}- toYaml . | nindent 8 {{close}}
      {{open}}- end {{close}}
      {{open}}- with .Values.{{component}}.tolerations {{close}}
      tolerations:
        {{open}}- toYaml . | nindent 8 {{close}}
      {{open}}- end {{close}}
      securityContext:
        {{open}}- toYaml .Values.{{component}}.podSecurityContext | nindent 8 {{close}}
      {{#if hostNetwork}}
      hostNetwork: true
      {{/if}}
      dnsPolicy: {{dnsPolicy}}
      containers:
        - name: {{component}}
          securityContext:
            {{open}}- toYaml .Values.{{component}}.securityContext | nindent 12 {{close}}
          image: "{{open}} .Values.{{component}}.image.repository {{close}}:{{open}} .Values.{{component}}.image.tag | default .Chart.AppVersion {{close}}"
          imagePullPolicy: {{open}} .Values.{{component}}.image.pullPolicy {{close}}
          ports:
          {{#each containerPorts}}
            {{this}}
          {{/each}}
          resources:
            {{open}}- toYaml .Values.{{component}}.resources | nindent 12 {{close}}
          {{#if hasEnvVars}}
          {{open}}- with .Values.{{component}}.envVars {{close}}
          env:
            - name: EXAMPLE_ENV_VAR
              value: {{open}} .exampleEnvVar | quote {{close}}
          {{open}}- end {{close}}
          {{/if}}
