apiVersion: v1
kind: Service
metadata:
  name: {{open}} include "{{component}}.fullname" . {{close}}
  namespace: {{open}} .Release.Namespace | quote {{close}}
  labels:
    {{open}}- include "{{component}}.labels" . | nindent 4 {{close}}
spec:
  type: {{open}} .Values.{{component}}.service.type {{close}}
  ports:
  {{#each svcPort}}
    {{{this}}}
  {{/each}}
  selector:
    {{open}}- include "{{component}}.selectorLabels" . | nindent 4 {{close}}
